version: '2.1'

services:

  app:
    image: neo:app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_DB_HOST=mongodb
    links:
      - mongodb
    ports:
      - 3001:3001

  mongodb:
    image: mongo:3.4.7
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: "exit 0"

  fetch:
    image: neo:app
    env_file:
      - .env
    environment:
      - MONGO_DB_HOST=mongodb
    links:
      - mongodb
    command: ["npm", "run", "fetch"]
